#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: func

# STEP: vivado_flow
cd /home/samaksh19200/Downloads
vivado -mode batch -nojournal -nolog -source /home/samaksh19200/Downloads/HLS_output//Synthesis/vivado_flow/vivado.tcl


