/* Generated by Yosys 0.11+10 (git sha1 4871d8f19, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = "Q5.v:1.1-13.10" *)
module Q5(A, B, C, Sum, Carry);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "Q5.v:2.13-2.14" *)
  input A;
  (* src = "Q5.v:3.13-3.14" *)
  input B;
  (* src = "Q5.v:4.13-4.14" *)
  input C;
  (* src = "Q5.v:6.13-6.18" *)
  output Carry;
  (* src = "Q5.v:5.13-5.16" *)
  output Sum;
  INV_X1 _15_ (
    .I(B),
    .ZN(_11_)
  );
  INV_X1 _16_ (
    .I(C),
    .ZN(_12_)
  );
  INV_X1 _17_ (
    .I(A),
    .ZN(_13_)
  );
  OR2_X1 _18_ (
    .A1(C),
    .A2(A),
    .Z(_14_)
  );
  INV_X1 _19_ (
    .I(_14_),
    .ZN(_00_)
  );
  OR2_X1 _20_ (
    .A1(_12_),
    .A2(_13_),
    .Z(_01_)
  );
  INV_X1 _21_ (
    .I(_01_),
    .ZN(_02_)
  );
  OR2_X1 _22_ (
    .A1(_11_),
    .A2(_00_),
    .Z(_03_)
  );
  INV_X1 _23_ (
    .I(_03_),
    .ZN(_04_)
  );
  OR2_X1 _24_ (
    .A1(_02_),
    .A2(_04_),
    .Z(Carry)
  );
  OR2_X1 _25_ (
    .A1(B),
    .A2(_14_),
    .Z(_05_)
  );
  INV_X1 _26_ (
    .I(_05_),
    .ZN(_06_)
  );
  OR2_X1 _27_ (
    .A1(_11_),
    .A2(_01_),
    .Z(_07_)
  );
  INV_X1 _28_ (
    .I(_07_),
    .ZN(_08_)
  );
  OR2_X1 _29_ (
    .A1(Carry),
    .A2(_06_),
    .Z(_09_)
  );
  INV_X1 _30_ (
    .I(_09_),
    .ZN(_10_)
  );
  OR2_X1 _31_ (
    .A1(_08_),
    .A2(_10_),
    .Z(Sum)
  );
endmodule
