/* Generated by Yosys 0.11+10 (git sha1 4871d8f19, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = "des1.v:1.1-23.10" *)
module des1(in, clk, out);
  (* src = "des1.v:1.29-1.32" *)
  input clk;
  (* src = "des1.v:9.46-9.47" *)
  wire d;
  (* src = "des1.v:1.19-1.21" *)
  input in;
  (* src = "des1.v:9.6-9.10" *)
  wire in11;
  (* src = "des1.v:9.17-9.21" *)
  wire in12;
  (* src = "des1.v:1.41-1.44" *)
  output out;
  (* src = "des1.v:9.28-9.30" *)
  wire q1;
  (* src = "des1.v:9.37-9.39" *)
  wire q2;
  (* src = "des1.v:9.54-9.56" *)
  wire q3;
  (* module_not_derived = 32'd1 *)
  (* src = "des1.v:14.8-14.39" *)
  SDFFX1 Ff1 (
    .CK(clk),
    .D(in11),
    .Q(q1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "des1.v:15.8-15.39" *)
  SDFFX1 Ff2 (
    .CK(clk),
    .D(in12),
    .Q(q2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "des1.v:18.8-18.36" *)
  SDFFX1 Ff3 (
    .CK(clk),
    .D(d),
    .Q(q3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "des1.v:11.10-11.24" *)
  CLKINVX1 Inv1 (
    in,
    in11
  );
  (* module_not_derived = 32'd1 *)
  (* src = "des1.v:12.10-12.24" *)
  CLKINVX1 Inv2 (
    in,
    in12
  );
  (* module_not_derived = 32'd1 *)
  (* src = "des1.v:20.10-20.23" *)
  CLKINVX1 Inv3 (
    q3,
    out
  );
  (* module_not_derived = 32'd1 *)
  (* src = "des1.v:17.9-17.23" *)
  XNOR2X1 Xnor1 (
    q1,
    q2,
    d
  );
endmodule
