/* Generated by Yosys 0.11+10 (git sha1 4871d8f19, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = "Q5.v:1.1-15.10" *)
module Q5(A, B, C, Sum, Carry);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "Q5.v:2.13-2.14" *)
  input A;
  (* src = "Q5.v:3.13-3.14" *)
  input B;
  (* src = "Q5.v:4.13-4.14" *)
  input C;
  (* src = "Q5.v:6.13-6.18" *)
  output Carry;
  (* src = "Q5.v:5.13-5.16" *)
  output Sum;
  INV_X1 _12_ (
    .I(B),
    .ZN(_08_)
  );
  INV_X1 _13_ (
    .I(C),
    .ZN(_09_)
  );
  INV_X1 _14_ (
    .I(A),
    .ZN(_10_)
  );
  NOR2_X1 _15_ (
    .A1(C),
    .A2(A),
    .ZN(_11_)
  );
  INV_X1 _16_ (
    .I(_11_),
    .ZN(_00_)
  );
  NOR2_X1 _17_ (
    .A1(_09_),
    .A2(_10_),
    .ZN(_01_)
  );
  INV_X1 _18_ (
    .I(_01_),
    .ZN(_02_)
  );
  NOR2_X1 _19_ (
    .A1(_08_),
    .A2(_11_),
    .ZN(_03_)
  );
  NOR2_X1 _20_ (
    .A1(_01_),
    .A2(_03_),
    .ZN(_04_)
  );
  INV_X1 _21_ (
    .I(_04_),
    .ZN(Carry)
  );
  NOR2_X1 _22_ (
    .A1(B),
    .A2(_00_),
    .ZN(_05_)
  );
  NOR2_X1 _23_ (
    .A1(_08_),
    .A2(_02_),
    .ZN(_06_)
  );
  NOR2_X1 _24_ (
    .A1(_04_),
    .A2(_06_),
    .ZN(_07_)
  );
  NOR2_X1 _25_ (
    .A1(_05_),
    .A2(_07_),
    .ZN(Sum)
  );
endmodule
